### PR TITLE
Housekeeping in the ib-kubernetes

### PR DESCRIPTION
**Pull request by almaslennikov**
Update go to 1.19 and the main dependencies to the latest versions
Add guthub actions
Adapt component for deployment on newer k8s versions

### CODE REVIEW

**Review by e0ne — APPROVED** [review]
LGTM

**Comment by moshe010** [comment]
@almaslennikov  why  CI failed?

**Review by moshe010 — COMMENTED** [review]
Please check why CI failed

**Review by moshe010 — APPROVED** [review]

**Pull request merged**
